Socket read buffering
Russian-AI-Cup-2017/cpp-cgdk pull request #5
Opened 2017-11-16 19:15 UTC by ud1

2017-11-16 19:37 UTC, adler3d requested changes
норм

2017-11-16 19:42 UTC, ud1 commented
Не понял коммента

2017-11-16 21:15 UTC, ud1 commented
Результат стратегии https://pastebin.com/raw/Npqqs1m4 против пустой стратегии.
Без оптимизации:
real    1m35.553s
user    0m15.312s
sys     0m31.536s

С оптимизацией:
real    0m46.800s
user    0m4.440s
sys     0m2.100s

2017-11-17 15:34 UTC, SladeThe commented
Нужно отформатировать код в соответствии с текущим стилем пакета. Например, открывающие фигурные скобки должны быть на той же строке. Между while и открывающей круглой скобкой должен быть пробел, вставить пробелы "1024*1024" или вообще заменить на "1 << 20".

С виду, остальное всё ОК. Можно будет замержить.

2017-11-17 18:34 UTC, ud1 commented
Поправил

2017-11-18 19:58 UTC, merged